name: 'Protodist'
description: 'Bundle and distribute protobuf packages'
inputs:
  git_host:
    description: 'git host'
    required: false
    default: "github.com"
  git_branch:
    description: 'git branch'
    required: true
  git_tag:
    description: 'git tag'
    required: false
  proto_out_dir:
    description: 'protobuf output directory'
    required: true
  git_owner:
    description: 'git owner'
    required: false
runs:
  using: docker
  image: 'Dockerfile'
  env:
    PROTODIST_GIT_OWNER: ${{inputs.git_owner}}
    PROTODIST_GIT_HOST: ${{inputs.git_host}}
    PROTODIST_GIT_BRANCH: ${{inputs.git_branch}}
    PROTODIST_GIT_TAG: ${{inputs.git_tag}}
    PROTODIST_PROTO_OUT_DIR: ${{inputs.proto_out_dir}}
#      - "--git_branch ${{inputs.git_branch}}"
#      - "--git_tag ${{inputs.git_tag}}"
#      - "--proto_dir ${{inputs.proto_dir}}"
#      - "--git_user ${{inputs.git_user}}"
#      - "--git_access_token ${{inputs.git_access_token}}"
#      - "--proto_import_path ${{inputs.proto_import_path}}"
#  args:
#    - "--git_branch ${{inputs.git_branch}}"
#    - "--git_tag ${{inputs.git_tag}}"
#    - "--proto_dir ${{inputs.proto_dir}}"
#    - "--git_user ${{inputs.git_user}}"
#    - "--git_access_token ${{inputs.git_access_token}}"
#    - "--proto_import_path ${{inputs.proto_import_path}}"